# Generated by Django 3.0.5 on 2020-05-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('date', models.DateField(verbose_name='дату поступления')),
                ('quantity', models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='цена')),
                ('provider', models.CharField(blank=True, max_length=256, verbose_name='имя поставщика')),
            ],
        ),
    ]
